import minipixels as mp
import minipixels.audio.audio as audio
import std.assert as a

function main(args)
  pack = mp.openAssetPack("build/tests/assets.mpx")
  a.assertTrue(typeof(pack) != "error", "asset pack opens")
  initialStats = mp.assetPackStats(pack)
  a.assertTrue(initialStats.lazyFile, "asset pack opens without retaining payloads")
  a.assertEq(initialStats.payloadMisses, 0, "asset open performs no payload reads")
  a.assertEq(initialStats.cachedPayloadBytes, 0, "asset open retains no payload bytes")
  img = mp.loadPngFromPack(pack, "hero")
  a.assertTrue(typeof(img) != "error", "packed png decodes")
  a.assertEq(img.width, 2, "packed png width")
  a.assertEq(img.height, 1, "packed png height")
  a.assertEq(img.getPixel(0, 0), mp.rgba(255, 0, 0, 255), "packed png first pixel")
  a.assertEq(img.getPixel(1, 0), mp.rgba(0, 0, 255, 255), "packed png second pixel")
  heroSlot = mp.assetSlotFromPack(pack, "hero")
  a.assertEq(mp.loadPngFromPackSlot(pack, heroSlot), img, "slot image access reuses decoded cache")
  large = mp.loadPngFromPack(pack, "large")
  a.assertTrue(typeof(large) != "error", "multi-block packed png decodes")
  a.assertEq(large.width, 129, "multi-block packed png width")
  a.assertEq(large.getPixel(128, 127), mp.rgba(17, 34, 51, 255), "multi-block packed png last pixel")
  generated = mp.loadPngFromPack(pack, "generated")
  a.assertTrue(typeof(generated) != "error", "procedural packed png decodes")
  a.assertEq(generated.width, 4, "procedural packed png width")
  a.assertEq(generated.getPixel(0, 0), mp.rgba(255, 128, 0, 255), "procedural packed png first pixel")
  tone = mp.loadBytesFromPack(pack, "tone")
  a.assertTrue(typeof(tone) == "bytes", "packed audio bytes load")
  a.assertEq(len(tone), 8, "packed audio byte length")
  a.assertEq(tone[0], 82, "packed audio first byte")
  a.assertEq(mp.assetKindFromPack(pack, "tone"), 2, "packed audio kind")
  toneAgain = mp.loadBytesFromPackSlot(pack, mp.assetSlotFromPack(pack, "tone"))
  a.assertEq(toneAgain, tone, "slot byte access reuses payload cache")
  stats = mp.assetPackStats(pack)
  a.assertTrue(stats.lazyFile, "MPX1 payloads remain file-backed")
  a.assertEq(stats.imageHits, 1, "image cache hit is measured")
  a.assertEq(stats.payloadHits, 1, "payload cache hit is measured")
  a.assertEq(stats.cachedPayloadBytes, 8, "only undecoded raw payload remains cached")
  repeatedA = mp.loadBytesFromPack(pack, "repeated_a")
  repeatedB = mp.loadBytesFromPack(pack, "repeated_b")
  a.assertTrue(typeof(repeatedA) == "bytes" and len(repeatedA) > 1000, "compressed file payload expands")
  a.assertEq(repeatedB, repeatedA, "deduplicated payload aliases decode equally")
  dedupStats = mp.assetPackStats(pack)
  a.assertEq(dedupStats.payloadMisses, stats.payloadMisses + 1, "deduplicated payload is read and decoded once")
  a.assertEq(dedupStats.decodedBytes, stats.decodedBytes + len(repeatedA), "deduplicated payload materializes once")
  encodedAudio = mp.loadBytesFromPack(pack, "tone_mp3")
  encodedClip = audio.clipFromBytes(encodedAudio, "packed-transcode")
  a.assertTrue(audio.prepareClip(encodedClip), "transcoded packed MP3 decodes")
  a.assertEq(encodedClip.codec, "mp3", "WAV asset is stored as MP3")
  a.assertTrue(mp.closeAssetPack(pack), "asset pack closes")
  closedRead = try(mp.loadBytesFromPack(pack, "tone"))
  a.assertTrue(typeof(closedRead) == "error", "closed asset pack rejects reads")

  bulkPack = mp.openAssetPack("build/tests/assets.mpx")
  a.assertTrue(typeof(bulkPack) != "error", "bulk asset pack opens")
  a.assertTrue(mp.preloadAssetPack(bulkPack, 16777216), "bulk preload succeeds")
  bulkStats = mp.assetPackStats(bulkPack)
  a.assertEq(bulkStats.bulkReads, 1, "small pack is loaded with one contiguous read")
  a.assertTrue(bulkStats.storedBytesRead > 0, "bulk preload reports physical bytes")
  a.assertTrue(bulkStats.decodedBytes >= bulkStats.storedBytesRead, "bulk preload reports decoded bytes")
  bulkHits = bulkStats.payloadHits
  mp.loadBytesFromPack(bulkPack, "tone")
  a.assertEq(mp.assetPackStats(bulkPack).payloadHits, bulkHits + 1, "bulk-preloaded payload is a cache hit")
  a.assertTrue(mp.closeAssetPack(bulkPack), "bulk asset pack closes")
  print "=== ASSET PACK TESTS DONE ==="
end function
